id: P010550
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD90124
  title: མཛོད་དགེ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    053c51a9ba4d41e99f56ac83ace878dc:
      image_group_id: I1PD90143
      title: ''
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
