id: I76D989B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:32:56+00:00'
last_modified: '2022-06-08T14:25:36.577353+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90124
  title: མཛོད་དགེ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5633':
      image_group_id: I1PD90143
      title: ''
      total_pages: 196
      order: 1
      base_file: 5633.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
